spring:
  application:
    name: weather-assistant-mcp
  ai:
    mcp:
      server:
        name: weather-assistant
        version: 1.0.0
  main:
    banner-mode: off

logging:
  level:
    root: ERROR

server:
  port: 8082

