spring:
  application:
    name: weather-mcp-server
  ai:
    mcp:
      server:
        name: weather-server
        version: 1.0.0
  main:
    banner-mode: off

logging:
  level:
    root: ERROR
server:
  port: 8081
